services:

  nginx:
    build:
      context: nginx
    depends_on:
      - mysql
    container_name: web-dev
    restart: unless-stopped
    volumes:
      - ./nginx/city.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/city.html:/usr/share/nginx/html/city.html
    ports:
      - 80:80
    networks:
      - 5blue-network

  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - 5blue-network
      
  redis:
    image: redis:6.0.20-alpine
    container_name: redis-dev
    restart: always
    volumes:
      - ./redis/db:/var/lib/redis
    networks:
      - 5blue-network

networks:
  5blue-network:
    ipam:
      config:
        - subnet: 192.168.110.0/24
